### ISSUE TITLE
Disable covoiturage-libre user tracking by large/evil companies

### ISSUE THREAD

**Issue by webplate** [covoiturage-libre/covoiturage-libre#176]
### Current Behavior 
As I was exploring the Javascript code I stumbled across two external loadings we impose on our users. Google Analytics and MixPanel are actually actively tracking our users. This is in my opinion a main issue as it tempers with our users privacy. This platform should not be another user information feeder/reseller !! I don't think this is the goal of the maintainers considering your stated purposes.

### Expected Behaviour 
I expect, in the communitarian spirit of the website, not to be spied by google when I'm on the website.

### Steps to Reproduce the Problem  
Visit any page of the official website... you're tracked !!

[] Development
[x] Production

### Ideas for solving the problem / Implementing the new functionality  
Remove google analytics and mixPanel loaders from our pages !
Use Piwik or another if you really need statistics.

This is such a shame to discover this scandal while diving into the code. I hope we can remedy this craziness soon and build a free/libre project deserving its name and not feeding Google etc...

@Poussinou , @nicolasleger @thb Did you know about this ? Does anyone reads the stats ? What do you think of my interpretation ?

**Comment by AlexBillbao** [comment]
Salut @webplate . Jusqu'ici @ndelavergne analysait les stats, et j'y ai également accès.
Ce sont des outils instructifs pour nous aiguiller sur le développement du projet.
Cela dit, je comprends ta remarque. 

Je prendrai le temps de regarder ce qu'est le "piwik" dont tu parles.

D'ici là, on peut rajouter dans les CGU que le site utilise Google analytics sur ses pages pour mieux comprendre l'usage du site par les usagers dans le but d'améliorer le service, et on peut préciser que si certains souhaitent ne pas être trackés, il peuvent installer sur leur navigateur le[ bloqueur de Google analytics](ttps://tools.google.com/dlpage/gaoptout?hl=FR.) que propose Google.  Qu'en penses-tu comme solution "court terme" ?

**Comment by webplate** [comment]
Hey @AlexBillbao :)

C'est super de voir ton travail sur les issues !

Piwik c'est ça:
https://piwik.org/

J'ai une instance donc je pourrais ajouter ça dans mon devis et le code et vous donner les accès pour remplacer GA (google analytics). Pas besoin donc à mon avis de modifier les CGUs.

En attendant, je serais curieux de voir le GA de covoiturage-libre... Vous m'invitez en PM (private message)?

**Comment by Poussinou** [comment]
@weplate go sur slack :)

**Comment by zamentur** [comment]
Plop, je veux bien proposer mon aide pour enlever/remplacer les trackers en question (dans la mesure du possible)

Les choses suivantes peuvent probablement être hébergées facilement et sans trop de difficultés plutôt que de leaker des infos comme actuellement via le referer:

- [ ] Browser update (update.js)
- [ ] Cloudflare (toastr.js et async.js)
- [ ] Font Google Apis

**A défaut l'inclusion d'une balise meta no-referer est plus que recommandée.**

Pour les trucs suivant c'est plus complexe car il s'agit de fonctionnalités, certaines peuvent être remplacées par des équivalents:

- [ ]  Google Analytics (par piwik)
- [ ] facebook connect (je comprend l'intérêt de ce choix pour votre projet, être compatible avec open id serait un plus cependant)
- [ ] Google.com (recaptcha.js, il y a d'autres librairies de captcha et inutile de le charger trop tot, idem inutile d'utiliser ce trucs de google qui leur sert à alimenter leurs IA en faisant bosser gratuitement les gens...)
- [ ] Map google (je ne sais pas si vous avez étudié la possibilité d'utiliser openstreetmap ?)
- [ ] DoubleClick (euh je sais pas d'où il sort lui ça semble juste être de la pub, peut être google anamytics qui charge ça ! )

Note au besoin je veux bien participer à la limitation de l'hémoragie des données de vos visiteurs...

**Comment by maxb29** [comment]
Salut @zamentur 
Ce dépôt correspond à l'ancienne version du site covoiturage-libre, qui n'est plus développé.
Le code source du nouveau site sera bientôt publié (ici ou ailleurs, je ne sais pas trop, ne faisant pas partie de l'équipe 'tech').
Ton aide est la bienvenue :)
Le plus simple est que tu envoies un mail à benevole@covoiturage-libre.fr pour être en contact direct avec l'équipe de dev.

**Comment by anubister** [comment]
Pour revenir sur le besoin, non seulement la protection des données est une chose importante dans l'absolue, mais surtout c'est un élément différenciant par rapport à BBC que vous affichez sur votre page d'accueil :
> Protéger les données des utilisateurs pour que celles-ci soient seulement consacrées au bon déroulement du covoiturage;
donc il faut veiller à ce que les faits correspondent aux paroles pour assurer votre crédibilité !

Pour la mise en oeuvre, je partage l'analyse de @webplate et @zamentur ; « y'a plus qu'à » !
Pour apporter ma petite pierre à l'édifice, pour le routage, ça peut valoir le coup de regarder du coté d'OpenRouteService https://openrouteservice.org/
